## Introd. a la Inteligencia Artificial
# Trabajo práctico clase 1 
### Consigna: entregar ejercicios del 1 al 9

### EJERCICIO 1

In [298]:
import numpy as np
ejemplo = np.array([[0, 1, 3, -4],[0, 0, 4, 6],[2, 4, 6, 8]], dtype='int8')


In [52]:
# Norma L0 = cantidad de valores distintos a cero para cada fila
def norm_0(matrix):
    r,c = matrix.shape
    print('la matriz tiene {} filas y {} columnas'.format(r,c))
    ones = np.divide(matrix, matrix)
    where_are_NaNs = np.isnan(ones)
    ones[where_are_NaNs] = 0
    suma = ones.sum(axis=1, dtype='int8')
    print(suma)
    
    return suma

In [53]:
norm_0(ejemplo)

la matriz tiene 3 filas y 4 columnas
[3 2 4]


C:\Users\AULAMU~1\AppData\Local\Temp/ipykernel_2732/276178715.py:5: RuntimeWarning: invalid value encountered in true_divide
  ones = np.divide(matrix, matrix)


array([3, 2, 4], dtype=int8)

In [54]:
# Norma L1 = suma de todos los valores absolutos de cada fila
def norm_1(matrix):
    r,c = matrix.shape
    print('la matriz tiene {} filas y {} columnas'.format(r,c))
    absolutos=np.abs(matrix)
    suma = absolutos.sum(axis=1)
    print(suma)
    return suma

In [55]:
norm_1(ejemplo)

la matriz tiene 3 filas y 4 columnas
[ 8 10 20]


array([ 8, 10, 20])

In [56]:
# Norma L2
def norm_2(matrix):
    r,c = matrix.shape
    print('la matriz tiene {} filas y {} columnas'.format(r,c))
    cuadrados = np.power(matrix,2)
    suma = np.sum(cuadrados, axis=1)
    raiz = np.sqrt(suma)
    print('L2 original', raiz)
    return raiz
    

In [57]:
norm_2(ejemplo)

la matriz tiene 3 filas y 4 columnas
L2 original [ 5.09901951  7.21110255 10.95445115]


array([ 5.09901951,  7.21110255, 10.95445115])

In [58]:
# Norma L-infinito: el valor máximo de los módulos de cada fila
def norm_inf(matrix):
    r,c = matrix.shape
    print('la matriz tiene {} filas y {} columnas'.format(r,c))
    absolutos=np.abs(matrix)
    maximo = absolutos.max(axis=1)
    print(maximo)
    return maximo
    

In [59]:
norm_inf(ejemplo)

la matriz tiene 3 filas y 4 columnas
[4 6 8]


array([4, 6, 8], dtype=int8)

### EJERCICIO 2

In [60]:
def norm_2_sorting(matrix):
    l2 = norm_2(matrix)
    indice = np.argsort(l2, axis=-1)[::-1]
    ordenada = np.sort(l2, axis=-1)[::-1]
    original_ordenada = np.take(matrix, indice, axis=0)
    print('L2 ordendada descendente', ordenada)
    print('matriz original:\n',matrix)
    print('original ordenada por L2 descendente:\n',original_ordenada)
    return original_ordenada


In [61]:
norm_2_sorting(ejemplo)

la matriz tiene 3 filas y 4 columnas
L2 original [ 5.09901951  7.21110255 10.95445115]
L2 ordendada descendente [10.95445115  7.21110255  5.09901951]
matriz original:
 [[ 0  1  3 -4]
 [ 0  0  4  6]
 [ 2  4  6  8]]
original ordenada por L2 descendente:
 [[ 2  4  6  8]
 [ 0  0  4  6]
 [ 0  1  3 -4]]


array([[ 2,  4,  6,  8],
       [ 0,  0,  4,  6],
       [ 0,  1,  3, -4]], dtype=int8)

### EJERCICIO 3

In [62]:
class userid(object):
        def __init__(self, users):
            self.users = np.array(users)
            self.index = np.arange(len(users))
            print('Indice: ',self.index)
            
        def id2idx(self, numero):
            indice = np.where(self.users==numero)
            if indice[0].size == 0:
                print('el usuario {} no se encuentra en la lista'.format(numero))
            else:
                print('el primer índice para el usuario {} es {}'.format(numero,indice[0][0]))
            return indice
        def idx2id(self, ind):
            if ind >= len(self.users):
                usuario = np.array([])
                print('el indice {} se encuentra fuera de rango'.format(ind))             
            else:
                usuario = self.users[ind]
                print('el usuario para el índice {} es {}'.format(ind,usuario))
            return usuario
    

In [63]:
nuevo=userid([3,4,5])

Indice:  [0 1 2]


In [64]:
nuevo.id2idx(4)

el primer índice para el usuario 4 es 1


(array([1], dtype=int64),)

In [65]:
nuevo.idx2id(2)

el usuario para el índice 2 es 5


5

In [66]:
nuevo.idx2id(3)

el indice 3 se encuentra fuera de rango


array([], dtype=float64)

In [67]:
nuevo.id2idx(8)

el usuario 8 no se encuentra en la lista


(array([], dtype=int64),)

### EJERCICIO 4

In [68]:
truth = np.array([1,1,0,1,1,1,0,0,0,1], dtype = bool)
prediction = np.array([1,1,1,1,0,0,1,1,0,0], dtype=bool)
print(truth, '\n',prediction )

[ True  True False  True  True  True False False False  True] 
 [ True  True  True  True False False  True  True False False]


In [69]:
def accuracy(truth, prediction):
    temp = np.logical_not(np.logical_xor(truth, prediction))
    suma = np.sum(temp)
    return suma/len(truth)

In [70]:
def tp(truth, prediction):
    suma = np.sum(np.logical_and(truth, prediction))
    return suma
def tn(truth, prediction):
    suma = np.sum(np.logical_and(np.logical_not(truth), np.logical_not(prediction)))
    return suma
def fn(truth, prediction):
    suma = np.sum(np.multiply(truth, np.logical_not(prediction)))
    return suma
def fp(truth, prediction):
    suma = np.sum(np.multiply(prediction, np.logical_not(truth)))
    return suma

In [71]:
def precision(truth, prediction):
    prec = tp(truth, prediction)/(tp(truth, prediction)+fp(truth, prediction))
    return prec
print(precision(truth, prediction))

0.5


In [72]:
def recall(truth, prediction):
    prec = tp(truth, prediction)/(tp(truth, prediction)+fn(truth, prediction))
    return prec
print(recall(truth, prediction))

0.5


In [73]:
def acc(truth, prediction):
    prec = (tp(truth, prediction)+tn(truth, prediction))/(tp(truth, prediction)+tn(truth, prediction)+fp(truth, prediction)+fn(truth, prediction))
    return prec
print(acc(truth, prediction))

0.4


### EJERCICIO 5

In [140]:
q_id = np.array([1,1,1,1,2,2,2,3,3,3,3,3,4,4,4,4],dtype='uint8')
t_r = np.array([1,0,1,0,1,1,1,0,0,0,0,0,1,0,0,1], dtype='float32')

In [240]:
def average_query_precision(q_id, t_r):
    if len(q_id) != len(t_r):
        print("los vectores deben ser de la misma dimensión")
        return
    else:
        promedio= 0
        i = np.min(q_id)
        for i in range(np.max(q_id)):
            temp = np.where(q_id == i+1)
            
            prom = np.mean(t_r[np.min(temp):np.max(temp)+1])
            promedio = promedio + prom
            print('el promedio parcial para el id {} es {}'.format(i+1,prom))
        promedio = promedio / np.max(q_id)
        print('Average Query Precision = ', promedio)
        return promedio

In [241]:
average_query_precision(q_id, t_r)

el promedio parcial para el id 1 es 0.5
el promedio parcial para el id 2 es 1.0
el promedio parcial para el id 3 es 0.0
el promedio parcial para el id 4 es 0.5
Average Query Precision =  0.5


0.5

### EJERCICIO 6

In [284]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]],dtype='float32')
c = np.array([[1, 0, 0], [0, 1, 1]], dtype='bool')
#print(c.shape[0])
print(np.linalg.norm((x-c[0,:]),axis=0))
#print(np.sum((x-c[0,:])))

[ 6.708204  9.643651 11.224972]


In [290]:
def dist(x,c):
    distancia =np.zeros((c.shape[0], x.shape[0]), dtype='float32')
    for i in range(c.shape[0]):
        dist = np.linalg.norm((x-c[i,:]),axis=0)
        distancia[i,:] = np.linalg.norm((x-c[i,:]),axis=0)
    print(distancia)
    return distancia
        
        
distancia = dist(x,c)
print(distancia.shape)

[[ 6.708204  9.643651 11.224972]
 [ 8.124039  8.124039  9.643651]]
(2, 3)


### EJERCICIO 7

In [303]:
vector = dist(x,c)


[[ 6.708204  9.643651 11.224972]
 [ 8.124039  8.124039  9.643651]]


2

In [296]:
indice = np.argmin(vector, axis=0)

In [297]:
indice

array([0, 1, 1], dtype=int64)

### EJERCICIO 8


In [307]:
import sklearn
from sklearn.datasets import load_iris

In [331]:
iris = load_iris()
print(type(iris))
X = np.array(iris.data[:, :3])
X.dtype
X.shape

<class 'sklearn.utils.Bunch'>


(150, 3)

In [366]:
def kmeans(clusters, datos, iteraciones):
    clasificacion = np.zeros(datos.shape[0])
    indices = np.array([x for x in range(0, datos.shape[0],1)])
    centroides = datos[np.random.choice(indices, size=(clusters),replace=False)]
    centroides = centroides[:,None]
    for x in range(iteraciones):
        #print(datos.shape)
        #print(centroides.shape)
        dist = np.linalg.norm(datos-centroides, axis=2)
        clasificacion = np.argmin(dist, axis=0)
        #print(dist.shape)
        #print(clasificacion.shape)
        for cluster in range(clusters):
            centroides[cluster] = np.mean(datos[clasificacion == cluster], axis =0)
    dist = np.linalg.norm(datos-centroides, axis=2) 
    clasificacion = np.argmin(dist, axis=0)
    print(centroides.shape)
    centroides = np.reshape(centroides, (centroides.shape[0], centroides.shape[2]))
    print(centroides.shape)
    return clasificacion, centroides

kmeans(4, X, 100)
    


(4, 1, 3)
(4, 3)


(array([2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 0, 0, 2, 0, 0, 0, 0,
        2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 0, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2,
        0, 2, 0, 2, 0, 2, 3, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 3, 3, 3, 3, 1, 3, 3, 3,
        3, 3, 3, 1, 1, 3, 3, 3, 3, 1, 3, 1, 3, 1, 3, 3, 1, 1, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 1, 3, 3, 3, 1, 3, 3, 1], dtype=int64),
 array([[5.37058824, 3.8       , 1.51764706],
        [5.84655172, 2.73275862, 4.3637931 ],
        [4.81818182, 3.23636364, 1.43333333],
        [6.83571429, 3.06428571, 5.6547619 ]]))

### EJERCICIO 9