## Introd. a la Inteligencia Artificial
# Trabajo práctico clase 2 
### Consigna: entregar ejercicios 1 y 2

### EJERCICIO 0 - C2   DATASETS SINTETICOS

In [76]:
import numpy as np
 

In [94]:
centroides = np.array([[1,0,0,0],[0,1,0,0]], dtype = 'uint64')
centroides[0] = np.multiply(centroides[0], np.random.randint(0,500))
centroides_A = np.reshape(centroides[0], (1,4))
centroides_B = np.reshape(centroides[1], (1,4))
n = 40
n2 = np.int_(n/2)
datos_A = np.repeat(centroides_A, n/2, axis=0)
datos_B = np.repeat(centroides_B, n/2, axis=0)
mu, sigma = 0, 4
datos_A_norm = datos_A + np.reshape(np.array([[np.random.normal(mu, sigma, np.int_(n/2))],[np.random.normal(mu, sigma, np.int_(n/2))],[np.random.normal(mu, sigma, np.int_(n/2))],[np.random.normal(mu, sigma, np.int_(n/2))]]),(np.int_(n/2),4))
datos_B_norm = datos_B + np.reshape(np.array([[np.random.normal(mu, sigma, n2)],[np.random.normal(mu, sigma, n2)],[np.random.normal(mu, sigma, n2)],[np.random.normal(mu, sigma, n2)]]),(n2,4))
indicador = np.reshape(np.array([np.zeros(n2),np.ones(n2)], dtype='bool'),(n,1))
indice = np.arange(n)
np.random.shuffle(indice)
completo = np.array([datos_A_norm,datos_B_norm])
completo = np.reshape(completo,(n,4))
completo_mix = completo[indice]
indicador_mix = indicador[indice]

print(indicador_mix)
print(completo_mix)

# El arreglo "indicador" contiene la información de a qué centroide corresponde cada fila del arreglo "completo_mix"

[[False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]]
[[ 4.39126976e+01 -3.17484731e+00  2.00382412e+00 -2.16663151e+00]
 [ 4.79685049e+01 -6.07450443e-01 -4.33382441e+00  2.86370457e+00]
 [ 3.40446521e+00 -3.57828146e-02 -1.79332350e+00 -2.95945280e+00]
 [ 5.37675165e+01 -5.21486578e+00  2.19948266e+00 -4.05235001e+00]
 [-1.40987557e+00 -2.63332851e+00 -8.48644354e+00  1.92942173e+00]
 [ 4.59815414e+01 -7.36695870e-01  2.23524042e+00  5.27068469e+00]
 [-1.75792590e+00 -4.19633799e+00 -6.46517679e-01  6.71122207e-01]
 [ 5.10388223e+01  1.89766391e+00 -6.07244005e+00  3.74452263e+00]
 [ 4.55898283e+01 -5.78516661e-01  5.73804940e+00  1.18368307e+00]
 [ 2.93126172e+00 -3.42496812e+00  1